// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

export type SessionSendParams = { apiKeyId: string, sessionId: string, messages: Array<UserInput>, };
